from pathlib import Path
import subprocess,sys,json,zipfile,hashlib,io
R=Path(r'E:\Github\lex-foster-language-companion');V=R/'verification/estate-quality-20261006';O=V/'lf-normalization';py=sys.executable
zip5=R/'dist/estate-quality-20261006-r5/Lex-Foster-Language-Companion-v0.1.1.zip';zip4=R/'dist/estate-quality-20261006-r4/Lex-Foster-Language-Companion-v0.1.1.zip';D=O/'native-r5';assert not D.exists()
results=[]
def run(label,args):
 p=subprocess.run(args,capture_output=True,text=True,encoding='utf-8',errors='replace');(O/(label+'.txt')).write_text(p.stdout+p.stderr,encoding='utf-8',newline='\n');results.append(dict(check=label,exit_code=p.returncode));print(label,p.returncode);assert p.returncode==0,p.stdout+p.stderr;return p
run('native-extraction',['powershell','-NoProfile','-Command',"Expand-Archive -LiteralPath '"+str(zip5)+"' -DestinationPath '"+str(D)+"'"])
ex=D/'lex-foster-language-companion-v0.1.1';skill=ex/'codex/lex-foster-language-companion'
run('native-runtime-tests',[py,'-B','-X','utf8','-m','unittest','discover','-s',str(skill/'scripts/tests'),'-v'])
run('package-tests',[py,'-B','-X','utf8','-m','unittest','discover','-s',str(R/'tests'),'-v'])
run('native-verifier',[py,'-B','-X','utf8',str(ex/'tools/verify_customer_release.py'),str(ex),'--outer',str(zip5),'--pretty'])
p=run('native-rebuild',[py,'-B','-X','utf8',str(ex/'tools/build_customer_release.py'),'--output',str(O/'rebuilt-r5')]);assert json.loads(p.stdout)['sha256']==hashlib.sha256(zip5.read_bytes()).hexdigest()
H=Path(r'C:\Users\user\.codex\plugins\cache\personal\scribe-hesperos-clearpath\0.1.3\skills\hesperos-documentation')
run('authorship-validation',[py,'-B','-X','utf8',str(H/'scripts/hesperos_authorship.py'),'validate','--root',str(R),'--receipt',str(V/'authorship-r5/documentation-authorship.json'),'--capability-entrypoint',str(H/'SKILL.md')])
comparisons=[]
def compare(a,b,prefix=''):
 with zipfile.ZipFile(a) as za,zipfile.ZipFile(b) as zb:
  assert za.namelist()==zb.namelist()
  for name in za.namelist():
   aa=za.read(name);bb=zb.read(name)
   if name.endswith('.zip'):compare(io.BytesIO(aa),io.BytesIO(bb),prefix+name+'/');continue
   if name.endswith(('release-manifest.json','SHA256SUMS.txt')):comparisons.append(dict(path=prefix+name,state='generated byte hashes updated'));continue
   assert aa.replace(b'\r\n',b'\n')==bb.replace(b'\r\n',b'\n'),name
   comparisons.append(dict(path=prefix+name,state='identical content after newline normalization'))
compare(zip4,zip5)
(O/'r5-checks.json').write_text(json.dumps(dict(candidate=str(zip5),sha256=hashlib.sha256(zip5.read_bytes()).hexdigest(),checks=results,reproducible=True,semantic_delta=False,r4_to_r5_members=comparisons,git_exact_evidence=str(O/'normalization.json')),indent=2)+'\n',encoding='utf-8',newline='\n')
print('All r5 checks passed; r4/r5 text content identical after line normalization')